# Generated by Django 5.1.2 on 2024-11-19 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero1', models.IntegerField()),
                ('numero2', models.IntegerField()),
                ('tipo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'alelos',
            },
        ),
        migrations.CreateModel(
            name='Crossmatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.IntegerField()),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_sex', models.CharField(max_length=10)),
                ('donor_birth_date', models.DateField()),
                ('donor_blood_type', models.CharField(max_length=3)),
                ('date_performed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crossmatch',
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exame', models.DateField()),
            ],
            options={
                'db_table': 'exames',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('tipo_sanguineo', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='CrossmatchPatientResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=100)),
                ('total_compatible_alleles', models.IntegerField()),
                ('total_incompatible_alleles', models.IntegerField()),
                ('crossmatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_results', to='backend.crossmatch')),
            ],
            options={
                'db_table': 'crossmatchpatientresult',
            },
        ),
        migrations.CreateModel(
            name='CrossmatchAlleleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allele_name', models.CharField(max_length=20)),
                ('allele_value', models.FloatField()),
                ('compatibility', models.BooleanField()),
                ('patient_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allele_results', to='backend.crossmatchpatientresult')),
            ],
            options={
                'db_table': 'crossmatchalleleresult',
            },
        ),
        migrations.CreateModel(
            name='ExameAlelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('alelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alelos', to='backend.alelo')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_alelos', to='backend.exame')),
            ],
            options={
                'db_table': 'exames_alelos',
            },
        ),
        migrations.AddField(
            model_name='exame',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='backend.paciente'),
        ),
    ]
